# Generated by Django 2.2.19 on 2021-02-21 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('type', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.Event')),
            ],
            options={
                'verbose_name': 'Ticket type',
                'verbose_name_plural': 'Ticket types',
            },
        ),
        migrations.CreateModel(
            name='OrderedTicket',
            fields=[
                ('type', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_ordered', to='events.Event')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.Reservation')),
            ],
            options={
                'verbose_name': 'Ordered ticket',
                'verbose_name_plural': 'Ordered tickets',
            },
        ),
    ]
